#
# Copyright (C) 2020 Signal Messenger, LLC.
# SPDX-License-Identifier: AGPL-3.0-only
#

[package]
name = "libsignal-ffi"
version = "0.1.0"
authors = ["Jack Lloyd <jack@signal.org>"]
edition = "2018"
license = "AGPL-3.0-only"

[lib]
name = "signal_ffi"
crate-type = ["staticlib"]

[dependencies]
libsignal-protocol-rust = { path = "../../protocol" }
libsignal-bridge = { path = "../shared", features = ["ffi"] }
async-trait = "0.1.41"
libc = "0.2"
futures = "0.3.7"
rand = "0.7.3"
static_assertions = "1.1"

[build-dependencies]
cbindgen = "0.15"
